name: ASP.NET CI
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    
    - name: Build app for release
      run: msbuild HelloWorldFrameworkTest\HelloWorldFrameworkTest.csproj -t:rebuild -verbosity:diag -property:Configuration=Release

