name: ASP.NET CI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - uses: nuget/setup-nuget@v2
        with:
          nuget-version: '5.x'
      - name: nuget pack
        run:  .\nuget.exe pack .\hello-world.nuspec 
      - name: Build app for release
        run: msbuild src\HelloWorldFrameworkTest.csproj -t:pack -verbosity:diag -property:Configuration=Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HelloWorld
          path: "D:/a/windows_build_example/windows_build_example/src/bin/Release/"

