name: Build Web App
 
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code
      - name: Setup .NET 6.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '4.x'
      - name: Display dotnet version
        run: |
          dotnet --version
          # msbuild -version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test with the dotnet CLI
        run: dotnet test --no-build
   
